### PR TITLE
Tttc merge

### PR DESCRIPTION
**Pull request by kjk001**
merge new archetypes and changed dependencies, so TTCMerge branch can be closed and further archetypes developed on new test branches

### CODE REVIEW

**Comment by kjk001** [comment]
I will leave this open so @JohN100x1 can decide if he actually wants all these changes

**Comment by JohN100x1** [comment]
cool I will have a look at the changes

**Review by JohN100x1 — COMMENTED** [review]
`CreateActivatableAbility`, `CreateWeaponEnchantment`, `CreateFeature`, `CreateAnswer` etc are replaced with a generic `CreateBlueprint` for creating the blueprints
This is a bug that will break the mod because defaults are set within these methods that cannot be null.

**Review by JohN100x1 — CHANGES_REQUESTED** [review]
- All `BlueprintBuff` previously created using `CreateBuff` should have the following defaults defined here:
```
public static BlueprintBuff CreateBuff(string name, Action<BlueprintBuff> init = null)
{
    var result = CreateBlueprint<BlueprintBuff>(name, bp => {
        bp.FxOnStart = new PrefabLink();
        bp.FxOnRemove = new PrefabLink();
    });
    init?.Invoke(result);
    return result;
}
```
- All `BlueprintActivatableAbility` previously created using `CreateActivatableAbility` should have the following defaults defined here:
```
public static BlueprintActivatableAbility CreateActivatableAbility(string name, Action<BlueprintActivatableAbility> init = null)
{
    var result = CreateBlueprint<BlueprintActivatableAbility>(name, bp => {
        bp.IsOnByDefault = true;
        bp.DeactivateImmediately = true;
        bp.ActivationType = AbilityActivationType.Immediately;
    });
    init?.Invoke(result);
    return result;
}
```
- All `BlueprintFeature` previously created using `CreateFeature` should have the following defaults defined here:
```
public static BlueprintFeature CreateFeature(string name, Action<BlueprintFeature> init = null)
{
    var result = CreateBlueprint<BlueprintFeature>(name, bp => {
        bp.Ranks = 1;
        bp.IsClassFeature = true;
    });
    init?.Invoke(result);
    return result;
}
```

**Comment by JohN100x1** [comment]
Everything else seems good to merge

**Pull request merged**
